'use strict';
const DEFAULTS={subreddits:'EarthPorn,CityPorn,wallpapers',sorting:'hot',topperiod:'week',changeinterval:20,refreshinterval:30,poolsize:50,minimumscore:100,allownsfw:false,allowvideos:false,showoverlay:true,showtitle:true,showsubreddit:true,showauthor:true,showscore:true,overlayautohide:true,fitmode:'cover',transition:'fade',transitionduration:1,debugmode:false};
const state={settings:{...DEFAULTS},pool:[],queue:[],shown:new Set(),bad:new Set(),active:0,current:null,changeTimer:null,refreshTimer:null,hideTimer:null,debugTimer:null,nextRefresh:0,lastUpdate:null,loading:false,generation:0};
const el={layers:[document.querySelector('#layer-a'),document.querySelector('#layer-b')],blur:document.querySelector('#blur'),overlay:document.querySelector('#overlay'),subreddit:document.querySelector('#subreddit'),title:document.querySelector('#title'),author:document.querySelector('#author'),score:document.querySelector('#score'),status:document.querySelector('#status'),debug:document.querySelector('#debug')};
function value(p){return p&&Object.prototype.hasOwnProperty.call(p,'value')?p.value:p}
function asBool(v){return v===true||v===1||v==='true'}
function cleanSettings(raw){const out={...state.settings};for(const k of Object.keys(DEFAULTS))if(raw[k]!==undefined)out[k]=value(raw[k]);for(const k of ['allownsfw','allowvideos','showoverlay','showtitle','showsubreddit','showauthor','showscore','overlayautohide','debugmode'])out[k]=asBool(out[k]);return out}
function persist(){try{localStorage.setItem('redditWallpaperPoolV1',JSON.stringify({savedAt:Date.now(),posts:state.pool.slice(0,100)}))}catch{}}
function restore(){try{const data=JSON.parse(localStorage.getItem('redditWallpaperPoolV1'));if(data&&Date.now()-data.savedAt<7*86400000&&Array.isArray(data.posts))state.pool=data.posts.filter(validPost).slice(0,100)}catch{}}
function validPost(p){return p&&typeof p.id==='string'&&/^https:\/\//.test(p.url)}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rebuildQueue(){let candidates=state.pool.filter(p=>!state.bad.has(p.id)&&!state.shown.has(p.id));if(!candidates.length){state.shown.clear();if(state.current)state.shown.add(state.current.id);candidates=state.pool.filter(p=>!state.bad.has(p.id)&&p.id!==state.current?.id)}state.queue=shuffle(candidates)}
function preload(post,timeout=15000){return new Promise((resolve,reject)=>{const img=new Image(),timer=setTimeout(()=>{img.src='';reject(new Error('Image timeout'))},timeout);img.onload=()=>{clearTimeout(timer);resolve(img)};img.onerror=()=>{clearTimeout(timer);reject(new Error('Image failed'))};img.referrerPolicy='no-referrer';img.src=post.url})}
async function nextImage(){if(!state.queue.length)rebuildQueue();for(let tries=0;tries<Math.max(state.pool.length,1);tries++){const post=state.queue.shift();if(!post)break;try{const img=await preload(post);show(post,img.src);const next=state.queue[0];if(next)preload(next).catch(()=>state.bad.add(next.id));return}catch(e){state.bad.add(post.id);console.warn('Skipping image',post.url,e)}}notify(state.pool.length?'No loadable images remain.':'No suitable image posts available.',true)}
function show(post,url){const incoming=1-state.active,outgoing=state.active;el.layers[incoming].src=url;el.layers[incoming].classList.add('active');el.layers[outgoing].classList.remove('active');state.active=incoming;state.current=post;state.shown.add(post.id);el.blur.style.backgroundImage='url("'+url.replace(/"/g,'%22')+'")';renderOverlay();scheduleChange()}
function score(n){return n>=1000000?(n/1000000).toFixed(1)+'m':n>=1000?(n/1000).toFixed(1)+'k':String(n)}
function renderOverlay(){const p=state.current,s=state.settings;el.overlay.style.display=s.showoverlay?'block':'none';if(!p)return;el.subreddit.textContent='r/'+p.subreddit;el.title.textContent=p.title;el.author.textContent='u/'+p.author;el.score.textContent=score(p.score);el.subreddit.hidden=!s.showsubreddit;el.title.hidden=!s.showtitle;el.author.hidden=!s.showauthor;el.score.hidden=!s.showscore;el.overlay.classList.remove('hidden');clearTimeout(state.hideTimer);if(s.overlayautohide)state.hideTimer=setTimeout(()=>el.overlay.classList.add('hidden'),5000)}
function scheduleChange(){clearTimeout(state.changeTimer);state.changeTimer=setTimeout(nextImage,Math.max(5,Number(state.settings.changeinterval)||20)*1000)}
function endpoint(){const s=state.settings,p=new URLSearchParams({subreddits:s.subreddits,sort:s.sorting,time:s.topperiod,limit:String(s.poolsize),minimumScore:String(s.minimumscore),allowNsfw:String(s.allownsfw),allowVideos:String(s.allowvideos)});return 'http://127.0.0.1:3847/posts?'+p}
async function refresh(force=false){if(state.loading)return;state.loading=true;const generation=state.generation;try{const r=await fetch(endpoint(),{cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Helper returned '+r.status);if(generation!==state.generation)return;const merged=new Map(state.pool.map(p=>[p.id,p]));for(const p of data.posts||[])if(validPost(p))merged.set(p.id,p);state.pool=[...merged.values()].sort((a,b)=>(b.createdUtc||0)-(a.createdUtc||0)).slice(0,Number(state.settings.poolsize)||50);state.lastUpdate=new Date();state.nextRefresh=Date.now()+Number(state.settings.refreshinterval)*60000;persist();rebuildQueue();if(!state.current&&state.pool.length)await nextImage();if(!state.pool.length)notify('No suitable image posts found.',true);else if(data.warning)notify(data.warning+' Using cached images.',true)}catch(e){console.warn(e);notify('Unable to load new Reddit posts. '+(state.pool.length?'Using cached images.':'Start the local helper.'),true);if(!state.current&&state.pool.length){rebuildQueue();await nextImage()}}finally{state.loading=false;scheduleRefresh()}}
function scheduleRefresh(){clearTimeout(state.refreshTimer);const ms=Math.max(60000,Number(state.settings.refreshinterval||30)*60000);state.nextRefresh=Date.now()+ms;state.refreshTimer=setTimeout(refresh,ms)}
function notify(message,sticky=false){el.status.textContent=message;el.status.classList.add('show');clearTimeout(el.status.timer);if(!sticky)el.status.timer=setTimeout(()=>el.status.classList.remove('show'),4000)}
function applyVisuals(){const s=state.settings;document.body.classList.toggle('contain',s.fitmode==='contain');document.body.classList.toggle('debug',s.debugmode);document.body.classList.remove('transition-none','transition-fade','transition-slow');document.body.classList.add('transition-'+s.transition);document.documentElement.style.setProperty('--duration',Math.max(0,Number(s.transitionduration)||0)+'s');renderOverlay()}
function applyProperties(props){const old=state.settings;state.settings=cleanSettings(props);applyVisuals();const apiKeys=['subreddits','sorting','topperiod','poolsize','minimumscore','allownsfw','allowvideos','refreshinterval'];if(apiKeys.some(k=>old[k]!==state.settings[k])){state.generation++;state.pool=[];state.queue=[];state.shown.clear();state.current=null;refresh(true)}if(old.changeinterval!==state.settings.changeinterval)scheduleChange()}
window.wallpaperPropertyListener={applyUserProperties:applyProperties};
function debugTick(){const remaining=Math.max(0,state.nextRefresh-Date.now()),minutes=Math.ceil(remaining/60000);el.debug.textContent='Pool: '+state.pool.length+'\nQueued: '+state.queue.length+'\nShown: '+state.shown.size+'\nNext refresh: '+minutes+'m\nLast API update: '+(state.lastUpdate?state.lastUpdate.toLocaleTimeString():'never');state.debugTimer=setTimeout(debugTick,1000)}
restore();applyVisuals();if(state.pool.length){rebuildQueue();nextImage()}refresh();debugTick();
