const http=require('node:http'),{getConfig}=require('./config'),{normalizeSubreddits}=require('./posts'),{TtlCache}=require('./cache'),{RedditClient}=require('./reddit');
const flag=v=>v==='1'||v==='true';
function integer(v,f,min,max){const n=Number.parseInt(v,10);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):f}
function parseQuery(url){const sort=['hot','new','top'].includes(url.searchParams.get('sort'))?url.searchParams.get('sort'):'hot',time=['hour','day','week','month','year','all'].includes(url.searchParams.get('time'))?url.searchParams.get('time'):'week';return{subreddits:normalizeSubreddits(url.searchParams.get('subreddits')||'EarthPorn'),sort,time,limit:integer(url.searchParams.get('limit'),50,1,100),minimumScore:integer(url.searchParams.get('minimumScore'),100,0,10000000),allowNsfw:flag(url.searchParams.get('allowNsfw')),allowVideos:flag(url.searchParams.get('allowVideos'))}}
function keyFor(q){return JSON.stringify(q)}
function send(res,status,body,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(body))}
function createServer(config=getConfig(),client=null){const reddit=client||new RedditClient(config),cache=new TtlCache(config.cacheTtlMs),stale=new Map();return http.createServer(async(req,res)=>{const origin=req.headers.origin;if(origin&&config.allowedOrigins.size&&!config.allowedOrigins.has(origin))return send(res,403,{error:'Origin not allowed'});const cors={'Access-Control-Allow-Origin':origin||'*',Vary:'Origin'};if(req.method==='OPTIONS'){res.writeHead(204,{...cors,'Access-Control-Allow-Methods':'GET, OPTIONS'});return res.end()}const url=new URL(req.url,'http://127.0.0.1');if(req.method!=='GET')return send(res,405,{error:'Method not allowed'},cors);if(url.pathname==='/health')return send(res,200,{ok:true,configured:Boolean(config.clientId&&config.clientSecret&&config.userAgent),cacheTtlSeconds:config.cacheTtlMs/1000},cors);if(url.pathname!=='/posts')return send(res,404,{error:'Not found'},cors);try{const q=parseQuery(url),key=keyFor(q),hit=cache.get(key);if(hit)return send(res,200,{posts:hit,cached:true,stale:false,fetchedAt:new Date().toISOString()},cors);try{const posts=await reddit.fetchPosts(q);cache.set(key,posts);if(posts.length)stale.set(key,posts);return send(res,200,{posts,cached:false,stale:false,fetchedAt:new Date().toISOString()},cors)}catch(e){const old=stale.get(key);if(old)return send(res,200,{posts:old,cached:true,stale:true,warning:e.message,fetchedAt:new Date().toISOString()},cors);throw e}}catch(e){return send(res,e.status||400,{error:e.message,retryAfter:e.retryAfter||null},cors)}})}
if(require.main===module){const config=getConfig();createServer(config).listen(config.port,'127.0.0.1',()=>console.log('Reddit Wallpaper Helper listening on http://127.0.0.1:'+config.port))}
module.exports={createServer,parseQuery,keyFor};
